In [25]:
#1. Importing Libraries
import numpy as np

import cv2



In [48]:
#3. Reading Image and Gray Scale Conversion
frame = cv2.imread(r'C:\Users\Junaid\images\body_count.jpg')  

gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) 


cv2.imshow("Images",frame)
cv2.imshow('gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()





In [49]:
#2.  Loading Pre-Trained Model 
body_classifier = cv2.CascadeClassifier(r'C:\Users\Junaid\images\haarcascade_fullbody.xml')

In [50]:
 #4. Extracting Bounding Boxes
bodies = body_classifier.detectMultiScale(gray)   

# 1.2 is the scale factor

# 3 is the minNeighbors

print(bodies)    

[[ 436   15  168  336]
 [  10   18  182  363]
 [ 678  103  166  332]
 [ 894  106  164  327]
 [1101   40  161  321]
 [ 482  588  137  273]
 [1106  886  180  359]
 [ 225  867  197  394]
 [  20  927  173  345]
 [ 661  872  204  407]
 [ 865  842  205  409]
 [ 528 1098   38   76]
 [ 262  303   52  105]
 [ 889  454  155  310]
 [ 226  434  196  393]
 [ 659  416  197  395]]


In [51]:
#5. Drawing Rectangle around detected bodies. 
i=0
for (x,y,w,h) in bodies:
    cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)
    i=i+1  #increment counter variable  
     # Display the box and faces
    cv2.putText(frame, 'Person: '+str(i), (x-20, y-20),cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
print("Total No. of person : ",i)


Total No. of person :  16


In [52]:
#6. Displaying Images
cv2.imshow('Humans',frame)

cv2.waitKey()

cv2.destroyAllWindows()

In [53]:


cap=cv2.VideoCapture(0)
while True:
    ret,img=cap.read()
    bodies = body_classifier.detectMultiScale(gray) 
    print(bodies)
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)
    cv2.imshow('Image',frame)
    if cv2.waitKey(0)==27 :
        break
        
cap.release()
cv2.destroyAllWindows()

[[ 436   15  168  336]
 [  10   18  182  363]
 [ 678  103  166  332]
 [ 894  106  164  327]
 [1101   40  161  321]
 [ 482  588  137  273]
 [ 225  867  197  394]
 [ 865  842  205  409]
 [1106  886  180  359]
 [  20  927  173  345]
 [ 661  872  204  407]
 [ 528 1098   38   76]
 [ 262  303   52  105]
 [ 889  454  155  310]
 [ 226  434  196  393]
 [ 659  416  197  395]]
[[ 436   15  168  336]
 [  10   18  182  363]
 [ 678  103  166  332]
 [ 894  106  164  327]
 [1101   40  161  321]
 [ 482  588  137  273]
 [1106  886  180  359]
 [ 225  867  197  394]
 [  20  927  173  345]
 [ 661  872  204  407]
 [ 865  842  205  409]
 [ 528 1098   38   76]
 [ 262  303   52  105]
 [ 659  416  197  395]
 [ 226  434  196  393]
 [ 889  454  155  310]]
[[ 436   15  168  336]
 [  10   18  182  363]
 [ 678  103  166  332]
 [ 894  106  164  327]
 [1101   40  161  321]
 [ 482  588  137  273]
 [1106  886  180  359]
 [ 225  867  197  394]
 [  20  927  173  345]
 [ 661  872  204  407]
 [ 865  842  205  409]
 [ 528 10

KeyboardInterrupt: 